repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: check-yaml
      - id: check-json
        exclude: "templates|.aws"
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]
  #    - id: flake8
  #      additional_dependencies:
  #        [
  #          "flake8-blind-except",
  #          "flake8-coding",
  #          "flake8-commas",
  #          "flake8-comprehensions",
  #          "flake8-deprecated",
  #          "flake8-docstrings",
  #          "flake8-meiqia",
  #          "flake8-mutable",
  #          "flake8-pep3101",
  #          "flake8-quotes",
  #          "flake8-string-format",
  #          "flake8-tidy-imports",
  #        ]

  #- repo: git@github.com:pre-commit/mirrors-yapf.git
  #  rev: v0.24.0
  #  hooks:
  #    - id: yapf
  #      exclude: "migrations|settings|scripts"
  #      additional_dependencies: ["futures"]
  #      args: ["--style=.style.yapf", "--parallel", "--in-place"]

  - repo: https://github.com/asottile/add-trailing-comma
    sha: v0.8.0
    hooks:
      - id: add-trailing-comma

  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]

  - repo: https://github.com/prettier/prettier
    rev: 1.16.4
    hooks:
      - id: prettier
        exclude: "templates|.aws"
